import { CheckCircle2, Clock, PauseCircle, Users, XCircle } from 'lucide-react';

import type { ColDef } from '@/types/onboarding';

export const COLUMNS: ColDef[] = [
  {
    id: 'lead',
    label: 'Leads',
    description: 'Fresh requests to qualify',
    icon: <Users className="w-3.5 h-3.5" />,
    accentText: 'text-semantic-blue-200',
    accentBg: 'bg-semantic-blue-500/10',
    accentBorder: 'border-semantic-blue-500/30',
    accentSolid: 'bg-semantic-blue-500',
    accentRing: 'ring-semantic-blue-500/30',
    cardBorder: 'border-l-semantic-blue-500',
  },
  {
    id: 'in_progress',
    label: 'In Progress',
    description: 'Active onboarding in motion',
    icon: <Clock className="w-3.5 h-3.5" />,
    accentText: 'text-secondary-pink-300',
    accentBg: 'bg-secondary-pink-500/10',
    accentBorder: 'border-secondary-pink-500/30',
    accentSolid: 'bg-secondary-pink-500',
    accentRing: 'ring-secondary-pink-500/30',
    cardBorder: 'border-l-secondary-pink-500',
  },
  {
    id: 'pending_review',
    label: 'Pending Review',
    description: 'Ready for checks & sign-off',
    icon: <PauseCircle className="w-3.5 h-3.5" />,
    accentText: 'text-secondary-yellow-300',
    accentBg: 'bg-secondary-yellow-500/10',
    accentBorder: 'border-secondary-yellow-500/30',
    accentSolid: 'bg-secondary-yellow-500',
    accentRing: 'ring-secondary-yellow-500/30',
    cardBorder: 'border-l-secondary-yellow-500',
  },
  {
    id: 'on_hold',
    label: 'On Hold',
    description: 'Paused waiting on updates',
    icon: <PauseCircle className="w-3.5 h-3.5" />,
    accentText: 'text-neutral-ochre-300',
    accentBg: 'bg-neutral-ochre-500/10',
    accentBorder: 'border-neutral-ochre-500/30',
    accentSolid: 'bg-neutral-ochre-500',
    accentRing: 'ring-neutral-ochre-500/30',
    cardBorder: 'border-l-neutral-ochre-500',
  },
  {
    id: 'completed',
    label: 'Completed',
    description: 'Done and ready in portal',
    icon: <CheckCircle2 className="w-3.5 h-3.5" />,
    accentText: 'text-primary-green-400',
    accentBg: 'bg-primary-green-500/10',
    accentBorder: 'border-primary-green-500/30',
    accentSolid: 'bg-primary-green-500',
    accentRing: 'ring-primary-green-500/30',
    cardBorder: 'border-l-primary-green-500',
  },
  {
    id: 'cancelled',
    label: 'Cancelled',
    description: 'Closed out or not proceeding',
    icon: <XCircle className="w-3.5 h-3.5" />,
    accentText: 'text-alert-red-300',
    accentBg: 'bg-alert-red-500/10',
    accentBorder: 'border-alert-red-500/30',
    accentSolid: 'bg-alert-red-500',
    accentRing: 'ring-alert-red-500/30',
    cardBorder: 'border-l-alert-red-500',
  },
];
